name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    environment: production
    strategy:
      matrix:
        node-version: [20.x, 22.x]

    name: Build with ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_API_URL: ${{ vars.NEXT_PUBLIC_BASE_API_URL }}
      NEXT_PUBLIC_APP_URL: ${{ vars.NEXT_PUBLIC_APP_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.10.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Run type checking
        run: pnpm check-types

      - name: Run lint
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test

      - name: Build project
        run: pnpm build

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests (Playwright)
        env:
          CI: true
          NODE_ENV: test
        run: npx playwright test
